### ISSUE TITLE
Add "help" command and man page

### ISSUE THREAD

**Issue by JuanjoSalvador** [JuanjoSalvador/dog#13]
Add a simply man page for the package, with a `-h ,--help` param to show some info about the package, like the ASCII logo, possible options and other significant information.

* [x] Help option
* [x] Man page

```
➜  dog-0.0.1 git:(master) ✗ dog --help | lolcat
          __
 |_______/ V`-,
  }        /~~  Dog, v0.0.4
 /_)^ --,r'
|b      |b


USAGE

    dog [OPTION] [OPTION PARAM]

EXAMPLE

    dog --message 'Hello World!'

AVAILABLE OPTIONS

    (no option)              Dog goes 'whoof'. Default option.
    -b, --bork               Dog goes 'bork'.
    -g, --guau               Dog goes 'guau' (spanish version).
    -m, --message            Dog will say your message.
    -f, --file  [FILE]       Dog will say every line of the specified file.
    -v, --version            Prints dog version.
    -w, --who-is-a-good-boy  Who's a good boy? You're a good boy!
```

**Comment by RandyKdev** [comment]
Good day, Can I give this a shot?

**Comment by JuanjoSalvador** [comment]
Hi @RandyKdev! I've just commited the help option, but the man page is still needed! Take it if you want.

**Comment by RandyKdev** [comment]
Ok @JuanjoSalvador, Let me give this a shot. Any particular preference on how the man page should be? or should I just follow the normal standard?

**Comment by JuanjoSalvador** [comment]
The standard one should be fine, no preferences about it.

**Comment by RandyKdev** [comment]
Ok
