### ISSUE TITLE
Makefile should create "bin" directory if not exists

### ISSUE THREAD

**Issue by JuanjoSalvador** [JuanjoSalvador/dog#16]
The compilation will fail if there isn't a `bin` directory when you launch the build, so the `Makefile` should be able to check this and create a proper directory before continue.

**Comment by RandyKdev** [comment]
Oh yeah, I faced this issue while working on issue #13.

I have fixed this in the makefile, can I submit a PR regarding this, before continuing with issue #13?

**Comment by JuanjoSalvador** [comment]
Actually there is a PR fixing this now, but go ahead!
