### ISSUE TITLE
[WIP/Windows] File option doesn't work on Windows

### ISSUE THREAD

**Issue by JuanjoSalvador** [JuanjoSalvador/dog#21]
The `--file` option doesn't work on Windows due to POSIX libraries not implemented on Windows compiler and the use of not standard C. The problem are mostly the use of `getline` and `sleep` functions.

A simple solution is avoiding this by replacing functions with standard C functions or replacing them with Windows compiler functions, not POSIX.

**Comment by IhToN** [comment]
getline removed in favor of fgets and made a new os_sleep function that will use either Windows Sleep or POSIX sleep function.

PR: #25

**Comment by JuanjoSalvador** [comment]
For the *nix version too or only for Windows?
